### ISSUE TITLE
Відповідність конвертованого ID реальному КОАТУУ

### ISSUE THREAD

**Issue by ValikDRV** [sokil/koatuu#1]
Вітаю, Дмитро!

Знайшов проблему відповідності ID в таблиці `level2` реальному КОАТУУ.
Для прикладу візьмемо Вінницьку область, Барський район:
Реальне КОАТУУ: 5202 (CSV: 520200000,,БАРСЬКИЙ РАЙОН/М.БАР.)
Значення конвертоване до таблиці: 502
![image](https://user-images.githubusercontent.com/8372269/54879490-1c3bcd00-4e42-11e9-947e-de6b561b195b.png)

Прошу виправити сценарій конвертації.
Дуже вдячний за Вашу роботу!

**Comment by sokil** [comment]
Привіт.

Я тут сам ледве згадав, що там відбувалося.
Стандартна довжина коду КОАТУУ 10 символів.

У Барського района код 9значний, доповнюємо нулем спереду: 0520200000
Маємо:
левел 1 код: 05 - код регіону
левел 1 тип: 2 - тип (регіону райони Автономної Республіки Крим, області)
левел 2 код: 02 - код міста
левел 2 тип: 0 - тип міста (нуль тут свідчить про те що це просто код групи одиниць)

Ід поля таблиці другого левела складається як левел 1 код + левел 2 код, тобто 0502, а оскільки в базі тип поля int, що не правильно, отримуємо код 502.

В таблицях левел 1 і 2 немає кодів коатуу, там є внутрішні коди, які забезпечують ієрархічність даних, ці дві таблиці представляють по суті області і райони. А в таблиці левел 3 уже повноцінний коаттуу, і вказівник на левел 1 і 2.

Змінив схему таблиці, тепер іди вставлятимуться з нулями. Також додав типии, і для таблиць мершого і другого рівня можна буде відновити коатуу
