### ISSUE TITLE
Associated Latitude, Longitude

### ISSUE THREAD

**Issue by justinelliotmeyers** [sokil/koatuu#3]
Do you know where I could find associated latitudes/ longitudes for these? I see polygons here: http://atu.minregion.gov.ua/ua/karta But not sure if a gis dataset exists somewhere?  Thank you!

**Comment by sokil** [comment]
Sorry, have no idea. Check https://www.geonames.org/export/ maybe there are coordinates for some cities.

**Comment by justinelliotmeyers** [comment]
Thanks for the quick response!
