### ISSUE TITLE
Нужно обновить

### ISSUE THREAD

**Issue by pomazanbohdan** [sokil/koatuu#4]
Возможно нужно добавить линк на https://data.gov.ua/dataset/dc081fb0-f504-4696-916c-a5b24312ab6e что бы можно было бы отслеживать обновление?

Потом у нас тут в скрипте https://github.com/OpenData835/datasets/blob/master/minjust/01/edr_loader/orgsupdater

есть обновлялка?
Может заюзать этот код и сделать проверку и авто скачку файла от туда?

**Comment by pomazanbohdan** [comment]
Я там пилю датасеты по всем реестрам открытых данных, с последующей разработкой платформы сведения и обработки этих данных с выдачей в апи. 
буду благодарен если присоединишься)
https://t.me/OpenData835

**Comment by sokil** [comment]
https://github.com/OpenData835/datasets/blob/master/minjust/01/edr_loader/orgsupdater

а от твоя лінка бита )))

**Comment by pomazanbohdan** [comment]
Да. переименовал репозиторий и поправил структуру внутри проекта
https://github.com/OpenData835/DatasetsUA/tree/master/minjust/opendata/01/edr_loader
