### ISSUE TITLE
Застарілі дані

### ISSUE THREAD

**Issue by mikelmi** [sokil/koatuu#6]
Тут присутні ліквідовані райони напр. Тарутинський.
Наприклад тут с. Булатівка відноситься до Тарутинського району, хоча тепер це Болградський район.
Схоже що актуальніші дані це отут - https://data.gov.ua/dataset/7f9d8b88-167a-4cd9-ad0d-4df5c0756c6e/resource/aedd8e4c-36d4-4376-b9e1-90859eeb9231

**Comment by sokil** [comment]
Привіт.

Якщо потрібні актуальні дані, там є скрипт по їх генерації

1) Качаємо базу http://www.ukrstat.gov.ua/klasf/st_kls/koatuu.zip
2) Конвертимо KOATUU_xxxxxxxx.xls file в csv
3) Конвертиму в мускуль дамп ./convert.py --source KOATUU_26042018.csv --format=mysql --target "db.sql"

Чи дані застрарілі саме в Укрстаті? ТОді нажаль нічим допомогти не можу, треба писати новий конвертер для актуальнішого дата сорса
